#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${KC_DB_USER} WITH PASSWORD '${KC_DB_PASSWORD}';
    CREATE DATABASE ${KC_DB_NAME} OWNER ${KC_DB_USER};
    GRANT ALL PRIVILEGES ON DATABASE ${KC_DB_NAME} TO ${KC_DB_USER};
EOSQL
